# backend/services/query_safety.py
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, Optional, Iterable


ALLOWED_TOP_LEVEL_KEYS = {
    "query",
    "aggs",
    "aggregations",
    "size",
    "from",
    "sort",
    "_source",
    "highlight",
    "track_total_hits",
    "search_after",
    "pit",
}

ALWAYS_EXCLUDE_FIELDS = [
    "event.original",
    "V2GCAM.DictionaryDimId",
    "log",
    "filename",
    "filename_path",
    "host",
    "@version",
]


class SafetyStatus(str, Enum):
    ALLOWED = "allowed"
    BLOCKED = "blocked"
    MODIFIED = "modified"


@dataclass
class ValidationResult:
    status: SafetyStatus
    query: Optional[Dict[str, Any]]
    reason: Optional[str]


class QuerySafetyLayer:
    """Validates and sanitises an Elasticsearch query body generated by an LLM.

    Implements the 5 safety rules from the design spec:
      1) Top-level key allowlist
      2) Recursive script detection
      3) Size cap enforcement
      4) _source exclusions injection
      5) Agg bucket cap for terms aggregations
    """

    def __init__(
        self,
        *,
        max_result_docs: int | None = None,
        max_agg_buckets: int | None = None,
        always_exclude_fields: list[str] | None = None,
    ):
        self.max_result_docs = int(max_result_docs if max_result_docs is not None else self._get_default_max_result_docs())
        self.max_agg_buckets = int(max_agg_buckets if max_agg_buckets is not None else self._get_default_max_agg_buckets())
        self.always_exclude_fields = list(ALWAYS_EXCLUDE_FIELDS if always_exclude_fields is None else always_exclude_fields)

    def _get_default_max_result_docs(self) -> int:
        try:
            from config import settings  # local import to avoid import-time env requirement in tests
            return int(settings.max_result_docs)
        except Exception:
            return 20

    def _get_default_max_agg_buckets(self) -> int:
        try:
            from config import settings  # local import to avoid import-time env requirement in tests
            return int(settings.max_agg_buckets)
        except Exception:
            return 50


    def validate(self, query: Dict[str, Any]) -> ValidationResult:
        if not isinstance(query, dict):
            return ValidationResult(
                status=SafetyStatus.BLOCKED,
                query=None,
                reason="query_not_a_dict",
            )

        # Rule 1: top-level allowlist
        for k in query.keys():
            if k not in ALLOWED_TOP_LEVEL_KEYS:
                return ValidationResult(
                    status=SafetyStatus.BLOCKED,
                    query=None,
                    reason=f"invalid_top_level_key:{k}",
                )

        # Rule 2: recursive script detection
        if self._contains_script(query):
            return ValidationResult(
                status=SafetyStatus.BLOCKED,
                query=None,
                reason="script_detected",
            )

        modified_reasons: list[str] = []

        # Rule 3: size cap
        if self._enforce_size_cap(query, self.max_result_docs):
            modified_reasons.append(f"size_capped_to_{self.max_result_docs}")

        # Rule 4: _source exclusions injection
        if self._inject_source_excludes(query, self.always_exclude_fields):
            modified_reasons.append("source_excludes_injected")

        # Rule 5: aggregation bucket caps
        if self._cap_agg_bucket_sizes(query, self.max_agg_buckets):
            modified_reasons.append(f"agg_buckets_capped_to_{self.max_agg_buckets}")

        if modified_reasons:
            return ValidationResult(
                status=SafetyStatus.MODIFIED,
                query=query,
                reason=";".join(modified_reasons),
            )

        return ValidationResult(status=SafetyStatus.ALLOWED, query=query, reason=None)

    # -----------------------
    # Rule implementations
    # -----------------------
    def _contains_script(self, obj: Any) -> bool:
        """Return True if key 'script' exists anywhere in obj."""
        if isinstance(obj, dict):
            for k, v in obj.items():
                if k == "script":
                    return True
                if self._contains_script(v):
                    return True
            return False
        if isinstance(obj, list):
            return any(self._contains_script(i) for i in obj)
        return False

    def _enforce_size_cap(self, query: Dict[str, Any], max_size: int) -> bool:
        """Caps top-level 'size' (if present) to max_size. Returns True if modified."""
        if "size" not in query:
            return False
        try:
            size_val = int(query.get("size", 0))
        except Exception:
            # Non-int size is suspicious; clamp it.
            query["size"] = max_size
            return True

        if size_val > max_size:
            query["size"] = max_size
            return True
        return False

    def _inject_source_excludes(self, query: Dict[str, Any], excludes: list[str]) -> bool:
        """Ensures '_source.excludes' contains the excludes list. Returns True if modified."""
        modified = False
        existing = query.get("_source")

        # ES allows:
        #   _source: true/false
        #   _source: ["fieldA", "fieldB"]  (includes)
        #   _source: {"includes": [...], "excludes": [...]}
        if existing is None:
            query["_source"] = {"excludes": list(excludes)}
            return True

        if isinstance(existing, bool):
            # Convert to dict so we can enforce exclusions consistently.
            if existing is False or existing is True:
                query["_source"] = {"excludes": list(excludes)}
                return True

        if isinstance(existing, list):
            # Treat as includes list.
            query["_source"] = {"includes": existing, "excludes": list(excludes)}
            return True

        if isinstance(existing, dict):
            # Merge into excludes
            current_excludes = existing.get("excludes")
            if current_excludes is None:
                existing["excludes"] = list(excludes)
                return True

            # Normalise current excludes to list[str]
            if isinstance(current_excludes, str):
                current_list = [current_excludes]
            elif isinstance(current_excludes, list):
                current_list = [str(x) for x in current_excludes]
            else:
                current_list = [str(current_excludes)]

            merged = list(dict.fromkeys(current_list + list(excludes)))  # preserve order, de-dupe
            if merged != current_list:
                existing["excludes"] = merged
                modified = True

            query["_source"] = existing
            return modified

        # Unexpected _source type -> overwrite with safe dict
        query["_source"] = {"excludes": list(excludes)}
        return True

    def _cap_agg_bucket_sizes(self, query: Dict[str, Any], max_buckets: int) -> bool:
        """Caps sizes on terms/significant_terms aggs anywhere in the aggs tree."""
        modified = False
        aggs = query.get("aggs") or query.get("aggregations")
        if not isinstance(aggs, dict):
            return False

        def walk(aggs_node: Dict[str, Any]) -> None:
            nonlocal modified
            for _agg_name, body in aggs_node.items():
                if not isinstance(body, dict):
                    continue

                for agg_type in ("terms", "significant_terms"):
                    if agg_type in body and isinstance(body[agg_type], dict):
                        params = body[agg_type]
                        if "size" in params:
                            try:
                                size_val = int(params["size"])
                            except Exception:
                                params["size"] = max_buckets
                                modified = True
                            else:
                                if size_val > max_buckets:
                                    params["size"] = max_buckets
                                    modified = True

                # Recurse into sub-aggs
                sub = body.get("aggs") or body.get("aggregations")
                if isinstance(sub, dict):
                    walk(sub)

        walk(aggs)
        return modified
