# docker-compose.yml

services:
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - gkg_net

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      chromadb:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - gkg_net

  chromadb:
    build: ./chromadb
    ports:
      - "8020:8000"  # host 8020 -> container 8000
    volumes:
      - chroma_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - gkg_net

networks:
  gkg_net:
    driver: bridge

volumes:
  chroma_data: